apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-postgres-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-delivery-postgres
  template:
    metadata:
      labels:
        app: food-delivery-postgres
    spec:
      terminationGracePeriodSeconds: 30
      hostname: food-delivery-postgres
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
      containers:
        - name: food-delivery-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: food-delivery-postgres-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: food-delivery-postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: food-delivery-postgres-volume
          persistentVolumeClaim:
            claimName: food-delivery-postgres-pvc
