name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create app settings for production
        env:
          APP_SETTINGS: FoodDelivery.FE/appsettings.Production.json
        run: |
          echo '{'> $APP_SETTINGS
          echo '  "ConnectionStrings": {' >> $APP_SETTINGS
          echo '    "DefaultConnection": "Server=food-delivery-postgres-svc.janik-ns.svc.cluster.local;Port=5432;Username=postgres;Password=${{ secrets.POSTGRES_PASSWORD }};Database=FoodDeliveryDB;",' >> $APP_SETTINGS
          echo '    "IdentityConnection": "Server=food-delivery-postgres-svc.janik-ns.svc.cluster.local;Port=5432;Username=postgres;Password=${{ secrets.POSTGRES_PASSWORD }};Database=FoodDeliveryUsersDB;"' >> $APP_SETTINGS
          echo '  },' >> $APP_SETTINGS
          echo '  "Stripe": {' >> $APP_SETTINGS
          echo '    "SecretApiKey": "${{ secrets.STRIPE_API_KEY }}",' >> $APP_SETTINGS
          echo '    "SecretWebhookKey": "${{ secrets.STRIPE_WEBHOOK_KEY }}"' >> $APP_SETTINGS
          echo '  }' >> $APP_SETTINGS
          echo '}' >> $APP_SETTINGS

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # https://github.com/actions-hub/kubectl
      - name: Update postgres secret step 1/2
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete secret food-delivery-postgres-secret --ignore-not-found

      - name: Update postgres secret step 2/2
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create secret generic food-delivery-postgres-secret --from-literal=password=${{ secrets.POSTGRES_PASSWORD }}

      - name: Deploy postgres database to Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f k8s/postgres

      - name: Deploy server to Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f k8s/server

      # because image tag is the same but its contents might have changed
      - name: Restart server deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment food-delivery-dep
